### ISSUE TITLE
FlexDriver IP

### ISSUE THREAD

**Issue by mwrnd** [acsl-technion/flexdriver-zuc#1]
I am stuck on the "need to acquire FlexDriver IP (`src/flc.dcp`) from NVIDIA Networking".

Any chance you could post an FPGA bitstream?

Or, could you provide any details with regard to how the ConnectX-5 is configured to send packets to the FPGA instead of the Host.

**Comment by ttsiodras** [comment]
Seconded! I raised the issue @mwrnd references above, because I want to react to packet reception and control transmission of packets from within the FPGA fabric of an Innova-2 board.

**Comment by haggaie** [comment]
Hi, thank you for your interest in FlexDriver. Unfortunately, NVIDIA cannot share the FlexDriver IP publically at this time, but please get in touch with me privately for more information.
